# Generated by Django 4.0.6 on 2023-04-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='picture',
            field=models.IntegerField(),
        ),
    ]
