# Generated by Django 4.0.6 on 2022-08-05 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='map',
            new_name='picture',
        ),
    ]
