# Generated by Django 4.0.6 on 2022-08-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_map_picture_rename_map_marker_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='picture',
        ),
    ]
