# Generated by Django 4.0.6 on 2022-08-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_marker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='top',
            field=models.FloatField(),
        ),
    ]
