# Generated by Django 4.0.6 on 2022-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_marker_left_alter_marker_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
