# Generated by Django 4.0.6 on 2022-09-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_marker_description_marker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='binomial_name',
        ),
    ]
